Task 1
funbiscuit/practice-platform-sync pull request #1
Opened 2024-06-29 22:07 UTC by re1ta

2024-06-30 13:28 UTC, funbiscuit commented on pom.xml
> +            <artifactId>spring-boot-starter-web</artifactId>
Кажется это тут лишнее

2024-06-30 13:28 UTC, funbiscuit commented on src/main/java/org/CliSystem/ApiDto.java
> +public class ApiDto {
Если правильно понял, тут больше подойдет `ModuleDto`
И ломбок в данном случае лишний, лучше использовать Java record.

2024-06-30 13:28 UTC, funbiscuit commented on src/main/java/org/CliSystem/ApiService.java
> +public class ApiService implements Callback<List<ApiDto>> {
Не понял назначения этого класса и для чего он реализует `Callback<List<ApiDto>>`

2024-06-30 13:28 UTC, funbiscuit commented on src/main/java/org/CliSystem/ApiService.java
> +    // TODO добавить metadata и script
Для выполнения первого задания надо заполнять script. И разбирать всю директор ю с файлами. То есть скорее всего где-то должен быть метод, принимающий путь к директории и возвращающий список со всеми модулями (ModuleDto)

2024-06-30 13:28 UTC, funbiscuit commented on src/main/java/org/CliSystem/RequestInterface.java
> +    Call<List<ApiDto>> saveModules(@Body ApiDto apiDto);
Такого эндпоинта нет, есть POST /api/v0/modules. И через него сохраняется только один модуль, а не список

2024-06-30 13:37 UTC, re1ta commented on pom.xml
> +            <artifactId>spring-boot-starter-web</artifactId>
это нужно для альтернативного метода с отправки запроса
RestTemplete(почти правильно написал) без этой зависимости не работает

2024-06-30 13:41 UTC, re1ta commented on src/main/java/org/CliSystem/ApiService.java
> +public class ApiService implements Callback<List<ApiDto>> {
я прочитал что у ретрофита есть две реализации отправки запроса: синхронная и ассинхронная, ну я выбрал второе, и для этого нужно Callback<List<ApiDto>> чтобы были методы обработки ответа запроса

2024-06-30 13:47 UTC, funbiscuit commented on src/main/java/org/CliSystem/ApiService.java
> +public class ApiService implements Callback<List<ApiDto>> {
Не надо асинхронными запросами заморачиваться, оставь синхронные, они заметно проще и читаемее

2024-06-30 13:48 UTC, funbiscuit commented on pom.xml
> +            <artifactId>spring-boot-starter-web</artifactId>
Тогда надо починить основной способ - через ретрофит. А другой способ убрать, и эту зависимость тоже

2024-07-01 06:24 UTC, funbiscuit requested changes

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/ApiService.java
> +        return "Что-то пошло не так";
Не, не, так делать точно не стоит. У тебя метод что вообще должен делать?

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +        String text = apiService.save(url,path);
Я предлагаю логику немного разделить и сделать отдельные этапы:
1. Парсим все файлы в директории и создаем из них отдельные объекты `ModuleObj`. Для этого лучше сделать отдельный сервис - `LocalModuleService`, у которого для этого будет метод `List<ModuleObj> parseModules(Path modulesDir)`. Думаю из сигнатуры понятно, как должен работать этот метод, что принимать и что возвращать. Если что-то не распарсилось - бросаем исключение (можно просто RuntimeException).
2. Получаем состояние модулей в платформе и для каждого создаем объект `ModuleDto`. Для этого тоже лучше сделать отдельный сервис - `RemoteModuleService`, у которого будет отдельный метод `List<ModuleDto> getModules()`. Тоже по сигнатуре должно быть понятно, как он работает. Адрес платформы надо передавать в конструктор `RemoteModuleService`.
3. Имея результаты из п.1 и п.2 можно найти все локальные модули, которых нет удаленно, и через `RemoteModuleService` их сохранить по отдельности. Для этого в `RemoteModuleService` надо сделать отдельный метод `void save(ModuleObj module)`.
4. Все ошибки наверх надо выкидывать исключениями, тут не go и не rust, возврат ошибок значениями работает очень плохо.
Соответственно текущий `ApiService` надо будет удалить (логика из него разойдется по новым сервисам)

И здесь ты сделал реализацию загрузки одного модуля, а надо парсить всю директорию.

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/ModuleDto.java
> +public class ModuleDto {
Тут тоже надо сделать record, тогда `@ToString` не будет нужен.

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/RequestInterface.java
> +public interface RequestInterface {
Лучше назвать `ModuleApi`

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/RequestInterface.java
> +    Call<ModuleDto> saveModules(@Body ModuleObj moduleObj);
Сохраняем один объект - поэтому `saveModule`, а не `saveModules`

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +    @CommandLine.Option(names = {"--target-url","-tu"}, description = "request to url")
Конечно конвенции есть разные, но я бы придерживался unix стиля для опций. А в нем короткие опции (с одним дефисом) всегда состоят из одной буквы. Т.е. `-tu` нельзя, можно либо `-t`, либо `-u`, либо какую-то еще букву. То же самое для опции для пути

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/ApiService.java
> +        if (path.endsWith(".py")) { path = path.substring(0, path.length() - ".py".length());}
Пожалуйста, форматируй код. В intellij это делается через `Alt+Shift+L`. Либо тыкни два раза `Shift` и найди какой у тебя шорткат для этого:
![image](https://github.com/funbiscuit/practice-platform-sync/assets/9351181/433b52da-4b68-4c22-9114-a7653d3ab7ac)

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/ApiService.java
> +        if (path.endsWith("init")) { path = path.substring(0, path.length() - "init".length() - 1);}
Не `init`, а `__init__`

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/ApiService.java
> +        if (path.endsWith(".py")) { path = path.substring(0, path.length() - ".py".length());}
Если у тебя путь не заканчивается на `.py`, то его вообще нельзя обрабатывать. Весь остальной код либо должен быть внутри `else`, либо надо поставить `return`.

2024-07-01 06:24 UTC, funbiscuit commented on src/main/java/org/CliSystem/ApiService.java
> +        if (index != -1) {
Если правильно понял, у тебя имя всегда включает `modules.`, а не должно. Для пути `modules/some.py` надо вернуть имя `some`.

2024-07-02 05:26 UTC, funbiscuit requested changes
tofix

2024-07-02 05:26 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +        remoteModuleService.saveAllNewModules(path);
Я не это имел в виду, в `RemoteModuleService` не надо делать метод `saveAllNewModules`. У этого сервиса одно предназначение - работать с удаленными модулями (получать список, сохранять, удалять). Определять "новый" модуль или нет не должно входить в его предназначение. Я предлагаю эту логику оставить прямо здесь, в CommandApi. А в сервисе оставить только `save` для сохранения одного модуля и `getAll` для получения всех модулей.

2024-07-02 05:26 UTC, funbiscuit commented on src/main/java/org/CliSystem/LocalModuleService.java
> +    private List<String> displayDirectory(File modulesDir, List<String> paths)
Так конечно тоже можно, но я бы предложил воспользоваться уже готовым `Files.walk`:

```java
List<Path> result;
try (Stream<Path> walk = Files.walk(path)) {
result = walk.filter(Files::isRegularFile)
        .collect(Collectors.toList());
}
```

И тогда не надо выносить отдельный метод `displayDirectory`, всю обработку можно делать в `parseModules`.

2024-07-02 05:26 UTC, funbiscuit commented on src/main/java/org/CliSystem/LocalModuleService.java
> +            return "Файл пуст!";
Так никогда не нужно делать. Если у тебя файл существует, но его нельзя прочитать (например, прав не хватает), то такой код все равно создаст в системе модуль со скриптом `Файл пуст!` и лови потом ошибки в проде. В данном методе у тебя нет никакого разумного способа обработать ошибку чтения файла, поэтому выкидывай исключение наверх.

2024-07-02 05:26 UTC, funbiscuit commented on src/main/java/org/CliSystem/ModuleApi.java
> +    Call<List<ModuleDto>> checkModules();
`check` намекает, что будет выполняться какая-то проверка, а это не так. Лучше назвать `getModules`. Или даже просто getAll, потому что у тебя этот Api только для модулей. Соответственно выше тоже можно назвать просто `save`, потому что итак понятно, что речь про модули.

2024-07-02 05:26 UTC, funbiscuit commented on src/main/java/org/CliSystem/RemoteModuleService.java
> +                .registerTypeAdapter(ModuleDto.class, new ModuleDtoDeserializer())
Для чего нужен отдельный адаптер, без него не работает?

2024-07-02 05:26 UTC, funbiscuit commented on src/main/java/org/CliSystem/RemoteModuleService.java
> +        ModuleApi service = retrofit.create(ModuleApi.class);
Не нужно создавать сервис для api в кажом методе. Создай в конструкторе и сохрани в `private final ModuleApi`. И тогда выносить отдельный метод `createRetro` тоже не придется, это можно будет сделать в констркуторе.

2024-07-02 05:26 UTC, funbiscuit commented on src/main/java/org/CliSystem/LocalModuleService.java
> +        if (path.endsWith(".py")) { path = path.substring(0, path.length() - ".py".length());}
Всё еще не вижу обработки ситуации, когда у нас не питоновский файл. По-хорошему, в этом методе ты уже ничего сделать не сможешь в таком случае, поэтому можно просто бросить исключение. А в `parseModules` фильтровать файлы - обрабатывать только питоновские. Тогда в `pathToName` подойдет `IllegalStateException`. Потому что в нем мы уже не должны оказаться с обработкой не питоновского файла. И если оказались, значит где-то что-то неправильно было сделано.

2024-07-02 13:12 UTC, re1ta commented on src/main/java/org/CliSystem/RemoteModuleService.java
> +                .registerTypeAdapter(ModuleDto.class, new ModuleDtoDeserializer())
да, не работает
он когда возвращает значение с запроса, он пытается засунуть значение в record и из-за этого выдаёт ошибку

2024-07-02 13:43 UTC, funbiscuit commented on src/main/java/org/CliSystem/RemoteModuleService.java
> +                .registerTypeAdapter(ModuleDto.class, new ModuleDtoDeserializer())
Надо пересесть с ~~иглы одобрения google~~ Gson на Jackson. Подключи зависимость `converter-jackson` вместо `converter-gson`. И тогда создание инстанса сервиса будет таким:
```java
        new Retrofit.Builder()
                .baseUrl(url)
                .addConverterFactory(JacksonConverterFactory.create(new ObjectMapper()))
                .build();
```
Jackson нормально работает с рекордами

2024-07-02 13:56 UTC, funbiscuit requested changes
tofix

2024-07-02 13:56 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +        List<ModuleObj> moduleObjs = remoteModuleService.filterNotInLocal(remoteModules, localModules);
Уже лучше, но вот содержимое fileterNotInLocal надо перенести сюда. Этого метода не должно быть в RemoteModuleService. Если хочешь отдельный метод - сделай его в этом классе `CommandApi`

2024-07-02 13:56 UTC, funbiscuit commented on src/main/java/org/CliSystem/LocalModuleService.java
>              moduleObjs.add(new ModuleObj(pathToName(path), pathToScript(path), null));
Лучше вместо null сохранить пустую `metadata` - `Map.of()`

2024-07-02 13:56 UTC, funbiscuit commented on src/main/java/org/CliSystem/LocalModuleService.java
> +            return sPath.substring(index).replace("\\", ".");
Это не кроссплатформенно. Слэши могут быть разные. Лучше сделать не через разбор строки, а использовать `Path`, который уже есть. В нем есть метод `iterator()` который как раз вернет тебе элементы пути. Которые можно собрать в список названий элементов:
```java
List<String> elements = StreamSupport.stream(path.spliterator(), false)
                .map(Path::toString)
                .toList();
```
А уже из них взять подсписок после `modules` и объединить через `String.join(".", elements)`.

2024-07-02 13:56 UTC, funbiscuit commented on src/main/java/org/CliSystem/LocalModuleService.java
> +        int index = sPath.indexOf("modules");
Не будет работать, если где-то в пути есть еще `modules`. Но можем пока закрыть глаза, оставить на потом.

2024-07-02 13:56 UTC, funbiscuit commented on src/main/java/org/CliSystem/LocalModuleService.java
> +            return String.valueOf(new RuntimeException());
Прекрасно (нет). Просто брось здесь RuntimeException.

2024-07-02 13:56 UTC, funbiscuit commented on src/main/java/org/CliSystem/RemoteModuleService.java
> +        ModuleApi service = retrofit.create(ModuleApi.class);
По-прежнему создаешь сервис в каждом методе, вынеси его.

2024-07-03 07:48 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
> +        List<ModuleObj> moduleObjs = remoteModuleService.filterNotInLocal(remoteModules, localModules);
Исправил
вынес метод в `CommandApi`

2024-07-03 07:49 UTC, re1ta commented on src/main/java/org/CliSystem/LocalModuleService.java
>              moduleObjs.add(new ModuleObj(pathToName(path), pathToScript(path), null));
Исправил
![Uploading 558ac90ae8b046e19438286b65d76a80.jpg…]()

2024-07-03 07:50 UTC, re1ta commented on src/main/java/org/CliSystem/LocalModuleService.java
> +            return sPath.substring(index).replace("\\", ".");
я конечно ваще удивляюсь как по-разному можно работать с данными... приятно удивляюсь!
исправил

2024-07-03 07:51 UTC, re1ta commented on src/main/java/org/CliSystem/LocalModuleService.java
> +        int index = sPath.indexOf("modules");
не исправил
сделаю позже

2024-07-03 07:52 UTC, re1ta commented on src/main/java/org/CliSystem/LocalModuleService.java
> +            return String.valueOf(new RuntimeException());
АХФВФЫБАВБЬВФАЫ, тут ваще мем я случайно написал `return` вместо `throw` и сидел и думал "а почему не работает"
исправил

2024-07-03 08:10 UTC, re1ta commented on src/main/java/org/CliSystem/RemoteModuleService.java
> +                .registerTypeAdapter(ModuleDto.class, new ModuleDtoDeserializer())
я сошёл с ~иглы одобрения гугл~!
исправил!

2024-07-03 08:25 UTC, funbiscuit requested changes
tofix

2024-07-03 08:25 UTC, funbiscuit commented on .gitignore
> -/.idea
Верни обратно .gitignore, который был. Добавляй только то, что действительно нужно  игнорировать.

2024-07-03 08:25 UTC, funbiscuit commented on src/main/java/org/CliSystem/ModuleDto.java
> +        @JsonProperty(value = "name") String name,
`@JsonProperty` здесь добавлять не нужно, потому что у тебя имя переменной совпадает с тем, что в json. Поэтому удали здесь и в остальных местах.

2024-07-03 08:28 UTC, re1ta commented on src/main/java/org/CliSystem/ModuleDto.java
> +        @JsonProperty(value = "name") String name,
```
java.lang.IllegalArgumentException: Unable to convert ModuleObj[name=some_dir.some_file1, script=# some 1, metadata={}] to RequestBody (parameter #1)
    for method ModuleApi.saveModule
```
не работает без аннотации

2024-07-03 08:31 UTC, re1ta commented on .gitignore
> -/.idea
я его не трогал вообще:((( он сам:(((
я вернул тот, который был в прошлых коммитах

2024-07-04 13:22 UTC, funbiscuit approved these changes

2024-07-04 13:22 UTC, merged