update_delete_modules
funbiscuit/practice-platform-sync pull request #3
Opened 2024-07-05 20:07 UTC by re1ta

2024-07-06 08:42 UTC, funbiscuit requested changes
tofix

2024-07-06 08:42 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +    public void deleteNotInLocal(List<ModuleDto> moduleDtos, List<ModuleObj> moduleObjs, RemoteModuleService remoteModuleService) {
По названиям переменных `moduleDtos` и `moduleObjs` не понятно что есть что. Предлагаю поменять на `localModules` и `remoteModules`

2024-07-06 08:42 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +        Set<String> objNames = moduleObjs.stream()
Тут можно добавит обратно guava и использовать `Sets.difference`.

2024-07-06 08:42 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +    public void updateNotInLocal(List<ModuleDto> moduleDtos, List<ModuleObj> moduleObjs, RemoteModuleService remoteModuleService) {
Как можно обновить модули, которых нет локально? Надо поменять название, скорее всего на `updateChanged`

2024-07-06 08:42 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +                .filter(obj -> moduleDtos.stream().noneMatch(dto -> dto.metadata().get("CheckSum").equals(obj.metadata().get("CheckSum"))))
Лучше на уровне `record` для обоих классов добавить метод `checksum`, который будет доставать контрольную сумму из метадаты.

2024-07-06 08:42 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +                .filter(obj -> moduleDtos.stream().noneMatch(dto -> dto.metadata().get("CheckSum").equals(obj.metadata().get("CheckSum"))))
Этот код содержит баг. Для воспроизведения создай новый модуль в test-pkg с новым содержимым. И тогда увидишь, что у тебя происходит попытка обновить этот модуль, хотя его еще нет в платформе.
Предлагаю изменить логику:
Получить `Sets.intersection` по именам модулей, чтобы получить те, которые есть и там, и там. Потом отфильтровать так, что для модуля локально у удаленного модуля контрольная сумма отличается (т.е. не через noneMatch, а прям брать конкретный удаленный модуль с таким же именем и сравнивать хэш

2024-07-06 08:42 UTC, funbiscuit commented on src/main/java/org/CliSystem/RemoteModuleService.java
> -        System.out.println(module);
На самом деле во все изменяющие операции (save, update, delete) добавить логирование (можно просто через System.out.println). Например, здесь надо вывести `Save module {name}`

2024-07-06 08:42 UTC, funbiscuit commented on src/main/java/org/CliSystem/RemoteModuleService.java
> +            throw new RuntimeException();
Так неправильно выкидывать исключения - теряется исходная информация об исключении. Сделай так:
```java
throw new RuntimeException("Failed to save module " + module.name(), e)
```
И в остальных местах тоже надо исправить

2024-07-06 08:42 UTC, funbiscuit commented on src/main/java/org/CliSystem/LocalModuleService.java
>              throw new RuntimeException(e);
Стоит добавить немного информации в исключение:
```java
throw new RuntimeException("Failed to parse local modules in " + moduleDir, e)
```

2024-07-06 08:42 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
>          List<ModuleObj> localModules = localModuleService.parseModules(path);
Для удобного сравнения локальных и удаленных модулей лучше хранить их в виде `Map<String, ModuleDto>` и `Map<String, ModuleObj>`, ключом брать имя модуля. Тогда через `keySet` можно быстро получить `Set` по именам модулей и дальше делать `Sets.difference` и `Sets.intersection`.

Поэтому из `parseModules` и `getModules` надо сразу возвращать `Map`

2024-07-07 23:50 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
> +    public void deleteNotInLocal(List<ModuleDto> moduleDtos, List<ModuleObj> moduleObjs, RemoteModuleService remoteModuleService) {
исправил

2024-07-07 23:51 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
> +    public void updateNotInLocal(List<ModuleDto> moduleDtos, List<ModuleObj> moduleObjs, RemoteModuleService remoteModuleService) {
исправил

2024-07-07 23:54 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
> +                .filter(obj -> moduleDtos.stream().noneMatch(dto -> dto.metadata().get("CheckSum").equals(obj.metadata().get("CheckSum"))))
Исправил

2024-07-07 23:56 UTC, re1ta commented on src/main/java/org/CliSystem/RemoteModuleService.java
> -        System.out.println(module);
Исправил

2024-07-07 23:58 UTC, re1ta commented on src/main/java/org/CliSystem/RemoteModuleService.java
> +            throw new RuntimeException();
Исправил

2024-07-07 23:59 UTC, re1ta commented on src/main/java/org/CliSystem/LocalModuleService.java
>              throw new RuntimeException(e);
Исправил

2024-07-08 00:42 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
> +        Set<String> objNames = moduleObjs.stream()
исправил

2024-07-08 00:49 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
>          List<ModuleObj> localModules = localModuleService.parseModules(path);
Исправил

2024-07-08 01:13 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
> +                .filter(obj -> moduleDtos.stream().noneMatch(dto -> dto.metadata().get("CheckSum").equals(obj.metadata().get("CheckSum"))))
Исправил

2024-07-08 06:38 UTC, funbiscuit requested changes
tofix

2024-07-08 06:38 UTC, funbiscuit commented on src/main/java/org/CliSystem/LocalModuleService.java
> +    public HashMap<String, ModuleObj> parseModules(String modulesDir) {
Тут тебе дальше не важно, что это именно `HashMap`, поэтому лучше возвратить интерфейс- `Map`. Точно так же, как раньше возвращал `List`, а не `ArrayList`. Это же касается и аргументов. Методы тоже по возможности должны принимать интерфейсы, а не конкретные реализации. Проверь и остальные методы.

2024-07-08 06:38 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
>          List<ModuleObj> moduleObjs = filterNotInLocal(remoteModules, localModules);
Предлагаю эту строчку и ту, что ниже, вынести в отдельный метод `saveNew`, а `filterNotInLocal` удалить (содержимое перенести в `saveNew`)

2024-07-08 06:38 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +                .filter(localModule -> !dtoNames.contains(localModule.name()))
Так здесь же тоже можно использовать `SetUtils.difference`

2024-07-08 06:38 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +        List<String> matchingModules = commonModules.stream()
Лучше назвать `changedModules`, а не `matching`

2024-07-08 06:38 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +                .filter(module -> !remoteModules.get(module).getCheckSum()
Лучше перед filter сделать `map(name -> localModules.get(name)` и при фильтрации уже сразу сравнивать с `remoteModules.get`, а в конце сразу делать `forEach` вместо `toList`

2024-07-08 20:18 UTC, re1ta commented on src/main/java/org/CliSystem/LocalModuleService.java
> +    public HashMap<String, ModuleObj> parseModules(String modulesDir) {
Исправил

2024-07-08 20:24 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
> +                .filter(localModule -> !dtoNames.contains(localModule.name()))
Мы же должны возращать лист объектов, а `SetUtils.difference` сравнивает только `Set` 
нам сначала надо будет достать имена из `ModuleObj`, потом сравнить `SetUtils.difference`, а потом через `contains` добавлять в `List`
разве это не дольше и не муторней?

2024-07-08 20:24 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
> +        List<String> matchingModules = commonModules.stream()
Исправил

2024-07-08 20:31 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
>          List<ModuleObj> moduleObjs = filterNotInLocal(remoteModules, localModules);
Исправил

2024-07-08 20:32 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
> +                .filter(module -> !remoteModules.get(module).getCheckSum()
Исправил

2024-07-09 04:50 UTC, funbiscuit requested changes
tofix

2024-07-09 04:50 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
>          moduleObjs.forEach(remoteModuleService::save);
Я же говорил, что строчку ниже тоже перенести в `saveNew`. То есть `saveNew` ничего не должен возвращать

2024-07-09 04:50 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
>          Set<String> commonModules = SetUtils.intersection(remoteModules.keySet(),localModules.keySet());
Можно же просто сделать `SetUtils.difference(localModules.keySet(), remoteModules.keySet())` чтобы получить названия модулей, которых нет удаленно. И дальше их сразу сохранять (сделав `map(name -> localModules.get(name)`).

2024-07-09 06:55 UTC, funbiscuit requested changes
tofix

2024-07-09 06:55 UTC, funbiscuit commented on src/main/java/org/CliSystem/CommandApi.java
> +        if (remoteModules.isEmpty()) {
Из-за этого условия код не работает, когда удаленных модулей нет, а локальные есть. В итоге ничего не сохраняется. У тебя в принципе эта проверка не нужна ни здесь, ни в остальных методах, так что удали её.

2024-07-09 15:30 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
>          moduleObjs.forEach(remoteModuleService::save);
исправил

2024-07-09 15:31 UTC, re1ta commented on src/main/java/org/CliSystem/CommandApi.java
>          Set<String> commonModules = SetUtils.intersection(remoteModules.keySet(),localModules.keySet());
исправил

2024-07-09 15:40 UTC, funbiscuit approved these changes
lgtm

2024-07-09 15:41 UTC, merged